---
title: "Data Visualization Project"
author: "Kat Vrotsos and Rachel Byers"
format: dashboard
embed-resources: true
orientation: rows
---

#  {.sidebar}

These charts are created from the 2024 National Survey on Drug Use and Health. 

```{r}
#| label: install-packages
#install.packages('tidyverse')
#install.packages('here')
#install.packages('rio')
#install.packages('janitor')
#install.packages('survey')
#install.packages('ggplot2')
```

```{r}
#| label: load-packages
library(tidyverse)
library(here)
library(rio)
library(janitor)
library(survey)
library(ggplot2)
```

```{r}
#| label: load-data

nsduh2024 <- import(here("NSDUH_2024.RData"), trust = TRUE) |>
  as_tibble() |>
  clean_names() |>
    select(questid2, analwt2_c, vestr_c, verep, catag6, irsex, newrace2, eduhighcat, govtprog,
         income, poverty3, health2, iralcage, irmjage, irstmnmage, illemflag2, stmnmlif,
         irpyud5alc, irpyud5mrj, ud5cnsany, ud5opiany2)

```

```{r}
#| label: format-data

# add labels, values, and turn into factors or character variables as needed

nsduh2024 <- nsduh2024 %>%
  mutate(poverty3 = as.factor(poverty3)) %>%
  mutate(irpyud5alc = as.factor(irpyud5alc))


#not sure where the list of variable types is coming from when rendered??
```

# Lab PS3: Visual from Project Data

## Row {height="80%"}

```{r}
#| title: 'First Visual'

ggplot(nsduh2024, aes(x = newrace2)) +
  geom_bar(fill = "steelblue") +
  theme_minimal() +
  labs(title = "Count of Race/Ethnicity", x = "Race/Ethnicity", y = "Count")
```
